routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'fw-block-bl'], function () {
    Auth::routes();

    Route::group(['prefix' => 'admin', 'middleware' => ['admin', 'isVerified', 'user-valid']], function () {
        Route::group(['prefix' => 'ingredients'], function () {
            Route::get('tree', 'IngredientController@tree');
            Route::get('pending', 'IngredientController@pending');
        });

        Route::group(['prefix' => 'recipes'], function () {
            Route::get('lists', 'RecipeController@admin_lists');
        });

        Route::group(['prefix' => 'clear'], function () {
            Route::get('all', 'ClearCacheController@all');
            Route::get('glasses', 'ClearCacheController@glasses');
            Route::get('measures', 'ClearCacheController@measures');
        });
    });

    Route::get('{path}', function($filename) {
        return Bust::css($filename);
    })->where('path', '.*\.css$');
    App::make('cachebuster.StripSessionCookiesFilter')->addPattern('|\.css$|');

    Route::group(['prefix' => 'me'], function() {
        Route::get('/', ['as' => 'user-profile.index', 'uses' => 'UserProfileController@index']);

        Route::group(['prefix' => '{username}'], function() {
            Route::get('/', ['as' => 'user-profile.show', 'uses' => 'UserProfileController@favorites']);
            Route::get('favorites', ['as' => 'user-profile.favorites', 'uses' => 'UserProfileController@favorites']);
            Route::get('recipes', ['as' => 'user-profile.recipes', 'uses' => 'UserProfileController@recipes']);
        });
    });

    Route::group(['prefix' => 'settings'], function() {
        Route::get('/', ['as' => 'user-settings.index.edit', 'uses' => 'UserSettingController@indexEdit']);
        Route::put('/', ['as' => 'user-settings.index.update', 'uses' => 'UserSettingController@indexUpdate']);

        Route::get('email', ['as' => 'user-settings.email.edit', 'uses' => 'UserSettingController@emailEdit']);
        Route::put('email', ['as' => 'user-settings.email.update', 'uses' => 'UserSettingController@emailUpdate']);

        Route::get('password', ['as' => 'user-settings.password.edit', 'uses' => 'UserSettingController@passwordEdit']);
        Route::put('password', ['as' => 'user-settings.password.update', 'uses' => 'UserSettingController@passwordUpdate']);

        Route::get('profile', ['as' => 'user-settings.profile.edit', 'uses' => 'UserSettingController@profileEdit']);
        Route::put('profile', ['as' => 'user-settings.profile.update', 'uses' => 'UserSettingController@profileUpdate']);
    });

    Route::get('email/error', ['as' => 'email-verification.error', 'uses' => 'Auth\RegisterController@getVerificationError']);
    Route::get('email/activate/{token}', ['as' => 'email-verification.check', 'uses' => 'Auth\RegisterController@getVerification', 'middleware' => ['throttle:10,10', 'clearUser']]);
    Route::get('email/resend', ['as' => 'email-verification.resend', 'uses' => 'UserSettingController@resendVerification', 'middleware' => 'throttle:5,10']);

    Route::group(['prefix' => 'login'], function() {
        Route::group(['prefix' => '{provider}', 'where' => ['provider' => '[a-z]+']], function() {
            Route::get('/', ['as' => 'oauth.redirect', 'uses' => 'OAuthController@redirect']);
            Route::get('callback', ['as' => 'oauth.callback', 'uses' => 'OAuthController@callback']);
        });
    });

    Route::get('/', ['as' => 'home', 'uses' => 'RecipeController@home']);

    Route::resource('ingredients', 'IngredientController', [
        'except' => [
            'index',
            'show'
        ],
        'parameters' => [
            'ingredients' => 'token'
        ]
    ]);

    Route::get('ingredients', ['as' => 'ingredients.index', 'uses' => 'IngredientController@show']);
    Route::get('ingredients/{parameters?}', ['as' => 'ingredients.show', 'uses' => 'IngredientController@show'])->where('parameters', '(.*)');

    Route::resource('recipes', 'RecipeController', ['except' => ['show']]);
    Route::get('recipes/{token}/{slug?}', ['as' => 'recipes.show', 'uses' => 'RecipeController@show'])->where('token', '[a-zA-Z0-9-]+')->where('slug', '[a-z0-9-]+');

    Route::group(['prefix' => 'ajax'], function() {
        Route::post('search/{type?}', ['before' => 'csrf', 'middleware' => 'throttle:30,5', 'as' => 'search-ajax', 'uses' => 'SearchController@ajax'])->where('type', '[A-Za-z]+');

        Route::post('recipe-image', ['before' => 'csrf', 'middleware' => 'throttle:15,5', 'as' => 'ajax_recipe_image', 'uses' => 'RecipeImageController@store']);

        Route::post('profile-image', ['before' => 'csrf', 'middleware' => 'throttle:15,5', 'as' => 'ajax_profile_image', 'uses' => 'UserSettingController@image']);

        Route::post('recipe-favorite', ['before' => 'csrf', 'middleware' => 'throttle:50,5', 'as' => 'ajax_recipe_favorite', 'uses' => 'UserFavoriteRecipeController@store']);
    });

    Route::post('search/{type?}', ['middleware' => 'throttle:30,5', 'as' => 'search', 'uses' => 'SearchController@search'])->where('type', '[A-Za-z]+');

//    Route::resource('occasions', 'OccasionController');

    Route::get('privacy', function() {echo 'Coming soon - Privacy Policy';});
    Route::get('terms', function() {echo 'Coming soon - Terms of Service';});
});

app/Http/Controllers/IngredientController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\Helper;
use App\Http\Requests\IngredientRequest;
use App\Ingredient;
use App\Recipe;
use Auth;
use Cache;
use Carbon\Carbon;

class IngredientController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'isVerified', 'user-valid'], ['only' => ['create']]);
        $this->middleware(['auth', 'isVerified', 'user-valid', 'throttle:20,5', 'xss'], ['only' => ['store']]);
        $this->middleware(['admin', 'isVerified', 'user-valid'], ['only' => ['edit', 'destroy']]);
        $this->middleware(['admin', 'isVerified', 'user-valid', 'xss'], ['only' => ['update']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $ingredients = Cache::remember('ingredients_root', 1440, function () {
            return Ingredient::whereIsRoot()->isActive()->isAlcoholic()->defaultOrder()->get();
        });

        return view('ingredients.index', compact('ingredients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $ingredient = [
            'title' => '',
            'ingredients' => ''
        ];
        $ingredients = ['' => '&nbsp;'];

        $nodes = Cache::remember('ingredients_tree', 1440, function () {
            return Ingredient::orderBy('is_alcoholic', 'desc')->orderBy('title')->get()->toTree();
        });

        $traverse = function ($ingredients_arr, $prefix = '-') use (&$traverse, &$ingredients) {
            foreach ($ingredients_arr as $val) {
                $pending = (!$val->is_active) ? ' (pending)': '';
                $ingredients[$val->token] = $prefix.' '.$val->title.$pending;
                $traverse($val->children, $prefix.'-');
            }
        };

        $traverse($nodes);
        return view('ingredients.create', compact('ingredient', 'ingredients'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\IngredientRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(IngredientRequest $request)
    {
        if (Auth::check()) {
            $user = Auth::user();
            $data = $request->all();

            $data['parent_id'] = null;
            $data['is_alcoholic'] = 0;
            $data['is_active'] = ($user->role == 1) ? 1 : 0;
            $data['user_id'] = Auth::id();

            if (!empty($data['ingredients'])) {
                $token = $data['ingredients'];

                $ingredient = Cache::remember('ingredient_TOKEN_'.$token, 1440, function () use ($token) {
                    return Ingredient::token($token)->first();
                });

                if ($ingredient) {
                    $data['parent_id'] = $ingredient->id;
                }
            }

            $ingredient = Ingredient::create($data);

            if (!empty($ingredient)) {
                $this->clear($ingredient);

                if ($data['is_active']) {
                    $ingredient_slug = $ingredient->slug;

                    if ($data['parent_id']) {
                        $ingredient_ancestors = Cache::remember('ingredient_ancestors_TOKEN_'.$ingredient->token, 1440, function () use ($ingredient) {
                            return $ingredient->ancestors()->select('id', 'token', 'title', 'slug')->get();
                        });

                        $ingredient_ancestors_self = array_merge($ingredient_ancestors->toArray(), [$ingredient->toArray()]);
                        $ingredient_ancestors_self_slug = array_pluck($ingredient_ancestors_self, 'slug');
                        $ingredient_slug = implode('/', $ingredient_ancestors_self_slug);
                    }

                    return redirect()->route('ingredients.show', $ingredient_slug)->with('success', 'Ingredient "'.$ingredient->title.'" has been created successfully.');
                }

                return redirect()->route('ingredients.create')->with('success', 'Ingredient "'.$ingredient->title.'" has been created successfully. Waiting on approval from admin.');
            }
        }

        return redirect()->back()->withInput()->with('danger', 'Ingredient create fail.');
    }

    /**
     * Display the specified resource.
     *
     * @param $parameters
     * @return \Illuminate\Http\Response
     */
    public function show($parameters = null)
    {
        $count_parameters = 0;
        $count_ingredient_valid = 0;

        if (!empty($parameters)) {
            $parameters_explode = explode('/', $parameters);
            $count_parameters = count($parameters_explode);
            $last_parameter = last($parameters_explode);

            $ingredient = Cache::remember('ingredient_SLUG_'.strtolower($last_parameter), 1440, function () use ($last_parameter) {
                return Ingredient::where('slug', $last_parameter)->isActive()->firstOrFail();
            });

            $ingredient_ancestors = Cache::remember('ingredient_ancestors_TOKEN_'.$ingredient->token, 1440, function () use ($ingredient) {
                return $ingredient->ancestors()->select('id', 'token', 'title', 'slug')->get();
            });

            $ingredient_ancestors_self = array_merge($ingredient_ancestors->toArray(), [$ingredient->toArray()]);
            $ingredient_ancestors_self_slug = array_pluck($ingredient_ancestors_self, 'slug');
            $count = 0;

            for ($count; $count < $count_parameters; $count++) {
                if (isset($ingredient_ancestors_self_slug[$count])) {
                    if ($parameters_explode[$count] == $ingredient_ancestors_self_slug[$count]) {
                        $count_ingredient_valid++;
                    }
                }
            }
        } else {
            $ingredients = Cache::remember('ingredients_root', 1440, function () {
                return Ingredient::whereIsRoot()->isActive()->isAlcoholic()->defaultOrder()->get();
            });
        }

        if ($count_parameters == $count_ingredient_valid) {
            $ingredient_descendants_id = [];

            if ($count_ingredient_valid > 0) {
                $recipe_month_text = 'ingredient_recipes_top_month_TOKEN_'.$ingredient->token;
                $ingredient_breadcrumbs = array_pluck($ingredient_ancestors_self, 'title', 'slug');

                $ingredients = Cache::remember('ingredient_children_TOKEN_'.$ingredient->token, 1440, function () use ($ingredient) {
                    return $ingredient->children()->orderBy('title')->get();
                });

                $ingredient_descendants = Cache::remember('ingredient_descendants_TOKEN_'.$ingredient->token, 1440, function () use ($ingredient) {
                    return $ingredient->descendants()->select('id', 'token', 'title', 'slug')->get();
                });

                if (!$ingredient_descendants->isEmpty()) {
                    $ingredient_descendants_id[] = $ingredient_descendants->pluck('id')->push($ingredient->id)->toArray();
                }
            } else {
                $recipe_month_text = 'ingredient_recipes_top_month';

                foreach($ingredients as $val) {
                    $ingredient_descendants = Cache::remember('ingredient_descendants_TOKEN_'.$val->token, 1440, function () use ($val) {
                        return $val->descendants()->select('id', 'token', 'title', 'slug')->get();
                    });

                    if (!$ingredient_descendants->isEmpty()) {
                        $ingredient_descendants_id[] = $ingredient_descendants->pluck('id')->push($val->id)->toArray();
                    }
                }
            }

            $now = Carbon::now()->minute(0)->second(0);
            $expiresAt = $now->copy()->minute(60);
            $total = 5;

            $recipes = Cache::remember($recipe_month_text, $expiresAt, function () use ($ingredient_descendants_id, $total) {
                return Recipe
                    ::join('recipe_counts', 'recipes.id', '=', 'recipe_counts.recipe_id')
                    ->select(['token', 'title', 'slug', 'recipe_counts.count_total as count_total'])
                    ->whereHas('ingredients', function ($query) use ($ingredient_descendants_id) {
                        $query->whereIn('ingredient_recipe.ingredient_id', array_unique(array_flatten($ingredient_descendants_id)));
                    })
                    ->where('recipe_counts.count_total', '>', $total)
                    ->orderBy('recipe_counts.count_total', 'DESC')
                    ->orderby('recipes.title')
                    ->take(10)
                    ->get();
            });

            return view('ingredients.show', compact('ingredient', 'ingredients', 'ingredient_breadcrumbs', 'recipes', 'parameters'));
        }

        abort(404);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Auth::check()) {
            $ingredient_data = Cache::remember('ingredient_TOKEN_'.$id, 1440, function () use ($id) {
                return Ingredient::token($id)->first();
            });

            if ($ingredient_data) {
                if (Helper::is_owner($ingredient_data->user_id)) {
                    $ingredients_token = null;

                    if ($ingredient_data->parent_id) {
                        $ingredient_parent_id = $ingredient_data->parent_id;

                        $parent = Cache::remember('ingredient_parent_TOKEN_'.$ingredient_data->token, 1440, function () use ($ingredient_parent_id) {
                            return Ingredient::select('token')->find($ingredient_parent_id);
                        });

                        if ($parent) {

resources/views/ingredients/create.blade.php
@extends('ingredients.template')

@section('title', 'Create New Ingredient')

@section('form')
    <form role="form" method="POST" action="{{ route('ingredients.store') }}">
@stop

resources/views/ingredients/edit.blade.php
@extends('ingredients.template')

@section('title', $ingredient['title'] . ' - Edit Ingredient')

@section('form')
<form role="form" method="POST" action="{{ route('ingredients.update', $ingredient['token']) }}">
    {{ method_field('PUT') }}
@stop

resources/views/ingredients/footer-option.blade.php
@if(Auth::check())
    @php
        $owner = false;
        $admin = false;

        if (Route::is('ingredients.show') && !empty($ingredient)) {
            $owner = Helper::is_owner($ingredient->user_id);
            $admin = Helper::is_admin();
        }
    @endphp
<div class="row">
    <div class="col-12 mt-3 text-right">
@if($admin)
        <form action="{{ route('ingredients.destroy', $ingredient->token) }}" method="post">
            {{ method_field('DELETE') }}
            {{ csrf_field() }}
@endif
            <div class="btn-group btn-group-sm" role="group" aria-label="">
                <a class="btn btn-secondary" href="{{ route('ingredients.create') }}"><i class="fa fa-plus-circle mr-1" aria-hidden="true"></i> New Ingredient</a>
@if($admin)
                <a class="btn btn-secondary" href="{{ route('ingredients.edit', $ingredient->token) }}"><i class="fa fa-pencil mr-1" aria-hidden="true"></i> Edit</a>
@endif
@if($admin)
                <button onclick="return confirm('Are you sure you want to delete?')" type="submit" class="btn btn-secondary"><i class="fa fa-trash-o mr-1" aria-hidden="true"></i> Delete</button>
@endif
            </div>
@if(Route::is('ingredients.show'))
        </form>
@endif
    </div>
</div>
@endif

resources/views/ingredients/index.blade.php
@extends('layouts.master')

@section('title', 'Ingredients')

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="row text-center">
                @foreach($ingredients as $ingredient)
                    <div class="col-12 col-sm-4 mb-4">
                        <div style="font-size: 20px;" class="card">
                            <a class="card-block" href="{{ route('ingredients.show', ['id' => $ingredient->slug]) }}">{!! $ingredient->title !!}</a>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>

    @include('ingredients.footer-option')
@stop

@section('sidebar-right')

@stop

resources/views/ingredients/pending.blade.php
@extends('layouts.master')

@section('title', 'Pending Lists - Ingredients')

@section('content')
    @if (!$ingredients->isEmpty())
        <div class="row">
            <div class="col-12">
                {{--<div class="list-group">
                    @foreach($ingredients as $ingredient)
                        @if(!empty($ingredients_slug[$ingredient->id]))
                            <a class="list-group-item list-group-item-action" href="{{ route('ingredients.edit', $ingredient->token) }}">{!! $ingredient->title !!} [{{ $ingredients_slug[$ingredient->id] }}]</a>
                        @endif
                    @endforeach
                </div>--}}

                <ul>
                    @foreach($ingredients as $ingredient)
                        @if(!empty($ingredients_slug[$ingredient->id]))
                            <li><a href="{{ route('ingredients.show', $ingredients_slug[$ingredient->id]) }}" target="_blank">{!! $ingredient->title !!}</a> [{{ $ingredients_slug[$ingredient->id] }}]</li>
                        @endif
                    @endforeach
                </ul>
            </div>
        </div>
    @endif
@stop

resources/views/ingredients/show.blade.php
@extends('layouts.master')

@php $title = (isset($ingredient->title)) ? $ingredient->title . ' - Ingredient' : 'Ingredients'; @endphp
@php $title_sup = (isset($ingredient->title_sup)) ? $ingredient->title_sup : 'Ingredients'; @endphp

@section('title', $title)

@section('breadcrumb')
    @if (!empty($ingredient_breadcrumbs))
        {!! Helper::breadcrumbs($ingredient_breadcrumbs, 'ingredients.show', 'Ingredients') !!}
    @endif
@stop

@section('content')
    <div class="row">
        <div class="col-12">
            <h1 class="mb-4">{!! $title_sup !!}</h1>

            @if (!$ingredients->isEmpty())
            <div class="row">
                {{--<div class="col-12">--}}
                    @php
                        $total = count($ingredients);
                        $mid = ceil($total/2);
                    @endphp
                    @foreach($ingredients as $val)
                        @if ($loop->iteration == 1 || $loop->iteration == ($mid+1))
                            @php $position = ($loop->iteration == 1) ? 'first' : 'last' @endphp
                            <div class="col-12 col-lg-6"><div class="list-group list-group-{{$position}}">
                        @endif
                        <a class="list-group-item list-group-item-action" href="{{ route('ingredients.show', $parameters) }}/{{ $val->slug }}">{!! $val->title !!}</a>
                        @if ($loop->iteration == $total || $loop->iteration == $mid)</div></div>@endif
                    @endforeach
                {{--</div>--}}
            </div>
            @endif
        </div>
    </div>

    @include('ingredients.footer-option')
@stop

@section('sidebar-right')
    @if (!$recipes->isEmpty())
    <div class="row">
        <div class="col-12">
            @if (isset($ingredient->title_sup))
                <h3 class="mb-0">Popular recipes</h3>
                {!! (isset($ingredient->title_sup)) ? '<h5>'.strtolower($ingredient->title_sup).'</h5>' : '' !!}
            @else
                <h3>Popular recipes</h3>
            @endif

            <ol>
            @foreach($recipes as $recipe)
                <li><a href="{{ route('recipes.show', ['token' => $recipe->token, 'slug' => $recipe->slug]) }}">{!! $recipe->title_sup !!}</a></li>
            @endforeach
            </ol>
        </div>
    </div>
    @endif
@stop

resources/views/ingredients/template.blade.php
@extends('layouts.master')

@section('style')
    <link rel="stylesheet" href="{{ Bust::url('/css/vendor/select2-bootstrap.css', true) }}">
@stop

@section('script-bottom')
    <script src="{{ Bust::url('/js/vendor/select2.min.js', true) }}"></script>
@stop

@section('content')
    <div class="row justify-content-center">
        <div class="col-12 col-md-8 col-lg-6">
            @yield('form')
                {{ csrf_field() }}
                {!! Honeypot::generate('first_name', 'my_time') !!}

                <div class="form-group{{ $errors->has('title') ? ' has-danger' : '' }}">
                    <label class="form-control-label" for="title" class="">Title</label>

                    <input id="title" type="text" class="form-control" name="title" value="{{ old('title', $ingredient['title']) }}" required autofocus>

                    @if ($errors->has('title'))
                        <div class="form-control-feedback">
                            <strong>{{ $errors->first('title') }}</strong>
                        </div>
                    @endif
                </div>

                @if (!empty($ingredients))
                <div class="form-group{{ $errors->has('ingredients') ? ' has-danger' : '' }}">
                    <label class="form-control-label" for="ingredients" class="">Parent of ingredient</label>

                    <select style="width: 100%;" class="form-control select2-set" name="ingredients" id="ingredients">
                        @foreach($ingredients as $key => $val)
                            <option value="{{ $key }}"@if(old('ingredients', $ingredient['ingredients']) == $key){{ 'selected' }}@endif @if(isset($ingredient['token'])) @if($ingredient['token'] == $key){{ 'disabled' }}@endif @endif>{{ $val }}</option>
                        @endforeach
                    </select>

                    @if ($errors->has('ingredients'))
                        <div class="form-control-feedback">
                            <strong>{{ $errors->first('ingredients') }}</strong>
                        </div>
                    @endif
                </div>
                @endif

                <div class="form-group">
                    <button class="btn btn-primary" type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
@stop

resources/views/ingredients/tree.blade.php
@extends('layouts.master')

@section('title', 'Tree - Ingredients')

@section('content')

    <style>
        .tree, .tree ul {
            font-size: 14px;
        }
        .tree, .tree ul, .tree li {
             position: relative;
        }

        .tree ul {
            list-style: none;
            padding-left: 32px;
        }

        .tree li::before, .tree li::after {
            content: "";
            position: absolute;
            left: -12px;
        }

        .tree li::before {
            border-top: 1px solid #000;
            top: 9px;
            width: 8px;
            height: 0;
        }

        .tree li::after {
            border-left: 1px solid #000;
            height: 100%;
            width: 0px;
            top: 2px;
        }
        
        .tree ul > li:last-child::after {
            height: 8px;
        }
    </style>

    @if (!empty($tree))
        <div class="tree">
        {!! $tree !!}
        </div>
    @endif
@stop