routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'fw-block-bl'], function () {
    Auth::routes();

    Route::group(['prefix' => 'admin', 'middleware' => ['admin', 'isVerified', 'user-valid']], function () {
        Route::group(['prefix' => 'ingredients'], function () {
            Route::get('tree', 'IngredientController@tree');
            Route::get('pending', 'IngredientController@pending');
        });

        Route::group(['prefix' => 'recipes'], function () {
            Route::get('lists', 'RecipeController@admin_lists');
        });

        Route::group(['prefix' => 'clear'], function () {
            Route::get('all', 'ClearCacheController@all');
            Route::get('glasses', 'ClearCacheController@glasses');
            Route::get('measures', 'ClearCacheController@measures');
        });
    });

    Route::get('{path}', function($filename) {
        return Bust::css($filename);
    })->where('path', '.*\.css$');
    App::make('cachebuster.StripSessionCookiesFilter')->addPattern('|\.css$|');

    Route::group(['prefix' => 'me'], function() {
        Route::get('/', ['as' => 'user-profile.index', 'uses' => 'UserProfileController@index']);

        Route::group(['prefix' => '{username}'], function() {
            Route::get('/', ['as' => 'user-profile.show', 'uses' => 'UserProfileController@favorites']);
            Route::get('favorites', ['as' => 'user-profile.favorites', 'uses' => 'UserProfileController@favorites']);
            Route::get('recipes', ['as' => 'user-profile.recipes', 'uses' => 'UserProfileController@recipes']);
        });
    });

    Route::group(['prefix' => 'settings'], function() {
        Route::get('/', ['as' => 'user-settings.index.edit', 'uses' => 'UserSettingController@indexEdit']);
        Route::put('/', ['as' => 'user-settings.index.update', 'uses' => 'UserSettingController@indexUpdate']);

        Route::get('email', ['as' => 'user-settings.email.edit', 'uses' => 'UserSettingController@emailEdit']);
        Route::put('email', ['as' => 'user-settings.email.update', 'uses' => 'UserSettingController@emailUpdate']);

        Route::get('password', ['as' => 'user-settings.password.edit', 'uses' => 'UserSettingController@passwordEdit']);
        Route::put('password', ['as' => 'user-settings.password.update', 'uses' => 'UserSettingController@passwordUpdate']);

        Route::get('profile', ['as' => 'user-settings.profile.edit', 'uses' => 'UserSettingController@profileEdit']);
        Route::put('profile', ['as' => 'user-settings.profile.update', 'uses' => 'UserSettingController@profileUpdate']);
    });

    Route::get('email/error', ['as' => 'email-verification.error', 'uses' => 'Auth\RegisterController@getVerificationError']);
    Route::get('email/activate/{token}', ['as' => 'email-verification.check', 'uses' => 'Auth\RegisterController@getVerification', 'middleware' => ['throttle:10,10', 'clearUser']]);
    Route::get('email/resend', ['as' => 'email-verification.resend', 'uses' => 'UserSettingController@resendVerification', 'middleware' => 'throttle:5,10']);

    Route::group(['prefix' => 'login'], function() {
        Route::group(['prefix' => '{provider}', 'where' => ['provider' => '[a-z]+']], function() {
            Route::get('/', ['as' => 'oauth.redirect', 'uses' => 'OAuthController@redirect']);
            Route::get('callback', ['as' => 'oauth.callback', 'uses' => 'OAuthController@callback']);
        });
    });

    Route::get('/', ['as' => 'home', 'uses' => 'RecipeController@home']);

    Route::resource('ingredients', 'IngredientController', [
        'except' => [
            'index',
            'show'
        ],
        'parameters' => [
            'ingredients' => 'token'
        ]
    ]);

    Route::get('ingredients', ['as' => 'ingredients.index', 'uses' => 'IngredientController@show']);
    Route::get('ingredients/{parameters?}', ['as' => 'ingredients.show', 'uses' => 'IngredientController@show'])->where('parameters', '(.*)');

    Route::resource('recipes', 'RecipeController', ['except' => ['show']]);
    Route::get('recipes/{token}/{slug?}', ['as' => 'recipes.show', 'uses' => 'RecipeController@show'])->where('token', '[a-zA-Z0-9-]+')->where('slug', '[a-z0-9-]+');

    Route::group(['prefix' => 'ajax'], function() {
        Route::post('search/{type?}', ['before' => 'csrf', 'middleware' => 'throttle:30,5', 'as' => 'search-ajax', 'uses' => 'SearchController@ajax'])->where('type', '[A-Za-z]+');

        Route::post('recipe-image', ['before' => 'csrf', 'middleware' => 'throttle:15,5', 'as' => 'ajax_recipe_image', 'uses' => 'RecipeImageController@store']);

        Route::post('profile-image', ['before' => 'csrf', 'middleware' => 'throttle:15,5', 'as' => 'ajax_profile_image', 'uses' => 'UserSettingController@image']);

        Route::post('recipe-favorite', ['before' => 'csrf', 'middleware' => 'throttle:50,5', 'as' => 'ajax_recipe_favorite', 'uses' => 'UserFavoriteRecipeController@store']);
    });

    Route::post('search/{type?}', ['middleware' => 'throttle:30,5', 'as' => 'search', 'uses' => 'SearchController@search'])->where('type', '[A-Za-z]+');

//    Route::resource('occasions', 'OccasionController');

    Route::get('privacy', function() {echo 'Coming soon - Privacy Policy';});
    Route::get('terms', function() {echo 'Coming soon - Terms of Service';});
});

app/Http/Controllers/RecipeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\RecipeRequest;
use App\Glass;
use App\Helpers\Helper;
use App\Ingredient;
use App\Measure;
use App\Recipe;
use App\RecipeCount;
use App\RecipeImage;
use App\Scopes\ActiveScope;
use App\User;
use App\UserFavoriteRecipe;
use Auth;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Cache;
use DB;

class RecipeController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'isVerified', 'user-valid'], ['only' => ['create', 'edit']]);
        $this->middleware(['auth', 'isVerified', 'user-valid', 'throttle:15,5', 'xss'], ['only' => ['store', 'update']]);
        $this->middleware(['admin', 'isVerified', 'user-valid'], ['only' => ['destroy']]);
    }

    public function home()
    {
        $now = Carbon::now()->second(0);
        $expiresAt = $now->copy()->minute(60);
        $expiresAtMinute = $now->copy()->addMinute();
        $total = 5;

        $recipes = Cache::remember('recipes_home', $expiresAt, function () use ($total) {
            return Recipe
                ::join('recipe_counts', 'recipes.id', '=', 'recipe_counts.recipe_id')
                ->join('users', 'recipes.user_id', '=', 'users.id')
                ->leftJoin('recipe_images', 'recipes.id', '=', 'recipe_images.recipe_id')
                ->select(['recipes.id', 'recipes.token', 'recipes.title', 'recipes.slug', 'recipes.description', 'recipes.directions', 'recipe_counts.count_total as count_total', 'recipe_images.image', 'users.id as user_id', 'users.image as user_image', 'users.display_name as user_display_name', 'users.username as username'])
                ->where('recipe_counts.count_total', '>', $total)
                ->inRandomOrder()
                ->take(24)
                ->get();
        });

        $favorite_recipes = collect([]);

        if (!$recipes->isEmpty()) {
            if (Auth::check()) {
                $user_id = Auth::id();
                $recipe_id = array_pluck($recipes, 'id');

                $favorite_recipes = Cache::remember('recipes_home_favorite_USERID_'.$user_id, $expiresAtMinute, function () use ($user_id, $recipe_id) {
                    return UserFavoriteRecipe::select('recipe_id')->where('user_id', $user_id)->whereIn('recipe_id', $recipe_id)->take(24)->pluck(null, 'recipe_id');
                });
            }
        }

        return view('recipes.home', compact('recipes', 'favorite_recipes'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $now = Carbon::now()->second(0);
        $expiresAt = $now->copy()->minute(60);
        $expiresAtMinute = $now->copy()->addMinute();
        $total = 5;

        $recipes = Cache::remember('recipes_latest', $expiresAt, function () use ($total) {
            return Recipe
                ::join('recipe_counts', 'recipes.id', '=', 'recipe_counts.recipe_id')
                ->join('users', 'recipes.user_id', '=', 'users.id')
                ->leftJoin('recipe_images', 'recipes.id', '=', 'recipe_images.recipe_id')
                ->select(['recipes.id', 'recipes.token', 'recipes.title', 'recipes.slug', 'recipes.description', 'recipes.directions', 'recipe_counts.count_total as count_total', 'recipe_images.image', 'users.id as user_id', 'users.image as user_image', 'users.display_name as user_display_name', 'users.username as username'])
                ->where('recipe_counts.count_total', '>', $total)
                ->orderby('recipes.created_at', 'DESC')
                ->orderby('recipes.title')
                ->take(24)
                ->get();
        });

        $favorite_recipes = collect([]);

        if (!$recipes->isEmpty()) {
            if (Auth::check()) {
                $user_id = Auth::id();
                $recipe_id = array_pluck($recipes, 'id');

                $favorite_recipes = Cache::remember('recipes_latest_favorite_USERID_'.$user_id, $expiresAtMinute, function () use ($user_id, $recipe_id) {
                    return UserFavoriteRecipe::select('recipe_id')->where('user_id', $user_id)->whereIn('recipe_id', $recipe_id)->take(24)->pluck(null, 'recipe_id');
                });
            }
        }

        $recipes_top = Cache::remember('recipes_popular', $expiresAt, function () use ($total) {
            return Recipe
                ::join('recipe_counts', 'recipes.id', '=', 'recipe_counts.recipe_id')
                ->select(['recipes.id', 'recipes.token', 'recipes.title', 'recipes.slug', 'recipe_counts.count_total as count_total'])
                ->where('recipe_counts.count_total', '>', $total)
                ->orderBy('recipe_counts.count_total', 'DESC')
                ->orderby('recipes.title')
                ->take(10)
                ->get();
        });

        return view('recipes.index', compact('recipes', 'favorite_recipes', 'recipes_top'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $recipe = [
            'title' => '',
            'description' => '',
            'directions' => '',
            'ingredients' => '',
            'ingredients_measure' => '',
            'ingredients_measure_amount' => '',
            'glass' => '',
        ];
        $ingredients = [];

        if (!empty(old('ingredients'))) {
            $ingredients_id = old('ingredients');
            $ingredient = [];

            $count = 0;

            foreach ($ingredients_id as $token) {
                $ingredient[] = Cache::remember('ingredient_TOKEN_'.$token, 1440, function () use ($token) {
                    return Ingredient::token($token)->first();
                });
            }

            if (!empty($ingredient)) {
                $ingredients = array_pluck($ingredient, 'title', 'token');
            }
        }

        $glasses_data = Cache::remember('glasses', 1440, function () {
            return Glass::select('id', 'title', 'slug')->orderBy('title')->get();
        });

        $measures_data = Cache::remember('measures', 1440, function () {
            return Measure::select('id', 'title', 'slug')->orderBy('title')->get();
        });

        $glasses = $glasses_data->pluck('title', 'slug')->all();
        $measures = $measures_data->pluck('title', 'slug')->all();

        return view('recipes.create', compact('recipe', 'ingredients', 'glasses', 'measures'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RecipeRequest $request)
    {
        if (Auth::check()) {
            $user = Auth::user();
            $data = $request->all();

            $glasses_data = Cache::remember('glasses', 1440, function () {
                return Glass::select('id', 'title', 'slug')->orderBy('title')->get();
            });

            $measures_data = Cache::remember('measures', 1440, function () {
                return Measure::select('id', 'title', 'slug')->orderBy('title')->get();
            });

            $glasses = $glasses_data->pluck('id', 'slug')->all();
            $measures = $measures_data->pluck('id', 'slug')->all();

            $data['description'] = Helper::textarea_to_array($data['description']);
            $data['directions'] = Helper::textarea_to_array($data['directions']);

            if (array_key_exists($data['glass'], $glasses)) {
                $data['glass_id'] = $glasses[$data['glass']];
            }

            $data['is_active'] = 1;
            $data['user_id'] = $user->id;

            $recipe = Recipe::create($data);

            if (!empty($recipe)) {
                $recipe->counts()->create([]);

                if (!empty($data['ingredients'])) {
                    $ingredients_data = [];
                    $ingredients = $data['ingredients'];
                    $count = 0;

                    foreach ($ingredients as $key => $token) {
                        if (!empty($token)) {
                            $ingredient = Cache::remember('ingredient_TOKEN_'.$token, 1440, function () use ($token) {
                                return Ingredient::token($token)->first();
                            });

                            if ($ingredient) {
                                $ingredients_data[$ingredient->id] = ['order_by' => $count++];

                                if (!empty($data['ingredients_measure'][$key])) {
                                    if (array_key_exists($data['ingredients_measure'][$key], $measures)) {
                                        $ingredients_data[$ingredient->id]['measure_id'] = $measures[$data['ingredients_measure'][$key]];
                                    }
                                }

                                if (!empty($data['ingredients_measure_amount'][$key])) {
                                    $ingredients_data[$ingredient->id]['measure_amount'] = Helper::fraction_to_decimal($data['ingredients_measure_amount'][$key]);
                                }
                            }
                        }
                    }

                    $recipe->ingredients()->sync($ingredients_data);
                }

                $this->clear($recipe);

                return redirect()->route('recipes.show', ['token' => $recipe->token, 'slug' => $recipe->slug])->with('success', 'Recipe "'.$recipe->title.'" has been created successfully.');
            }
        }

        return redirect()->back()->withInput()->with('danger', 'Recipe create fail.');
    }

    /**
     * Display the specified resource.
     *
     * @param $parameter
     * @return \Illuminate\Http\Response
     */
    public function show($token = null, $slug = null, Request $request)
    {
        if (!empty($token) && empty($slug)) {
            $slug = $token;

resources/views/recipes/admin-lists.blade.php
@extends('layouts.master')

@section('title', 'Lists - Recipes')
@section('content')
    @if (!$recipes->isEmpty())
        <div class="row">
            <div class="col-12">
                @foreach($recipes as $recipe)
                    @php $matched = []; @endphp

                    <hr>
                    <div class="row">
                        <div class="col-2">
                            <a href="{{ route('recipes.show', ['token' => $recipe->token, 'slug' => $recipe->slug]) }}" target="_blank">{!! $recipe->title !!}</a>
                            @php
                                $test = app('profanityFilter')->replaceWith('#')->replaceFullWords(false)->filter($recipe->slug, true);

                                if (isset($test['hasMatch'])) {
                                    $matched[] = $test['matched'];
                                }

                                $test = app('profanityFilter')->replaceWith('#')->replaceFullWords(false)->filter($recipe->title, true);

                                if (isset($test['hasMatch'])) {
                                    $matched[] = $test['matched'];
                                }
                            @endphp
                        </div>

                        <div class="col-4">
                            <p>{{ $recipe->description }}</p>
                            @php
                                $test = app('profanityFilter')->replaceWith('#')->replaceFullWords(false)->filter($recipe->description, true);

                                if (isset($test['hasMatch'])) {
                                    $matched[] = $test['matched'];
                                }
                            @endphp
                        </div>

                        <div class="col-5">
                            <ol>
                                @foreach($recipe->directions as $val)
                                    <li class="float-left ml-2">{{ $val }}</li>
                                    @php
                                        $test = app('profanityFilter')->replaceWith('#')->replaceFullWords(false)->filter($val, true);

                                        if (isset($test['hasMatch'])) {
                                            $matched[] = $test['matched'];
                                        }
                                    @endphp
                                @endforeach
                            </ol>
                        </div>

                        <div class="col-1">
                            @if (!empty($matched))
                                @foreach(array_flatten($matched) as $val)
                                    <span class="badge badge-danger">{{ $val }}</span>
                                @endforeach
                            @endif
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    @endif
@stop

resources/views/recipes/create.blade.php
@extends('recipes.template')

@section('title', 'Create New Recipe')

@section('form')
    <form role="form" method="POST" action="{{ route('recipes.store') }}">
@stop

resources/views/recipes/edit.blade.php
@extends('recipes.template')

@section('title', $recipe['title'] . ' - Edit Recipe')

@section('form')
<form role="form" method="POST" action="{{ route('recipes.update', $recipe['token']) }}">
    {{ method_field('PUT') }}
@stop

resources/views/recipes/footer-option.blade.php
@if(Auth::check())
    @php
        $owner = false;
        $admin = false;

        if (Route::is('recipes.show') && !empty($recipe)) {
            $owner = Helper::is_owner($recipe->user_id);
            $admin = Helper::is_admin();
        }
    @endphp
<div class="row mb-4">
    <div class="col-12 my-3 text-md-right">
@if($admin)
        <form action="{{ route('recipes.destroy', $recipe->token) }}" method="post">
            {{ method_field('DELETE') }}
            {{ csrf_field() }}
@endif
            <div class="btn-group btn-group-sm" role="group" aria-label="">
                <a class="btn btn-secondary" href="{{ route('recipes.create') }}"><i class="fa fa-plus-circle mr-1" aria-hidden="true"></i> New Recipe</a>
@if($owner)
                <a class="btn btn-secondary" href="{{ route('recipes.edit', $recipe->token) }}"><i class="fa fa-pencil mr-1" aria-hidden="true"></i> Edit</a>
@endif
@if($admin)
                <button onclick="return confirm('Are you sure you want to delete?')" type="submit" class="btn btn-secondary"><i class="fa fa-trash-o mr-1" aria-hidden="true"></i> Delete</button>
@endif
            </div>
@if($admin)
        </form>
@endif
    </div>
</div>
@endif

resources/views/recipes/home.blade.php
@extends('layouts.master')

@section('title', 'Home')

@php $random_color = []; @endphp

@section('content')
    @if(!empty($recipes))
    <div class="row">
        <div class="col-12">
            <div class="row">
                @foreach($recipes as $recipe)
                    @php
                        if (!isset($random_color[$recipe->user_id])) {
                            $random_color[$recipe->user_id] = Helper::get_cache_random_color($recipe->user_id);
                        }
                    @endphp
                <div class="col-12 mb-5 col-md-6 mb-md-4 col-lg-4">
                    @include('layouts.recipe-card', compact('random_color'))
                </div>
                @endforeach
            </div>
        </div>
    </div>
    @endif
@stop

resources/views/recipes/index.blade.php
@extends('layouts.master')

@section('title', 'Recipes')

@php $random_color = []; @endphp

@section('content')
    @if(!$recipes->isEmpty())
    <div class="row mb-4">
        <div class="col-12">
            <h3>Latest Recipes</h3>

            <hr>

            <div class="row">
                @foreach($recipes as $recipe)
                    @php
                        if (!isset($random_color[$recipe->user_id])) {
                            $random_color[$recipe->user_id] = Helper::get_cache_random_color($recipe->user_id);
                        }
                    @endphp
                <div class="col-12 mb-5 col-lg-6 mb-lg-4">
                    @include('layouts.recipe-card', compact('random_color'))
                </div>
                @endforeach
            </div>
        </div>
    </div>
    @endif

    @include('recipes.footer-option')
@stop

@section('sidebar-right')
    @if(!$recipes_top->isEmpty())
    <div class="row">
        <div class="col-12">
            <h3>Popular Recipes</h3>

            <ol>
            @foreach($recipes_top as $recipe)
                <li>
                    <a href="{{ route('recipes.show', ['token' => $recipe->token, 'slug' => $recipe->slug]) }}">{{ $recipe->title }}</a>
                </li>
            @endforeach
            </ol>
        </div>
    </div>
    @endif
@stop