routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'fw-block-bl'], function () {
    Auth::routes();

    Route::group(['prefix' => 'admin', 'middleware' => ['admin', 'isVerified', 'user-valid']], function () {
        Route::group(['prefix' => 'ingredients'], function () {
            Route::get('tree', 'IngredientController@tree');
            Route::get('pending', 'IngredientController@pending');
        });

        Route::group(['prefix' => 'recipes'], function () {
            Route::get('lists', 'RecipeController@admin_lists');
        });

        Route::group(['prefix' => 'clear'], function () {
            Route::get('all', 'ClearCacheController@all');
            Route::get('glasses', 'ClearCacheController@glasses');
            Route::get('measures', 'ClearCacheController@measures');
        });
    });

    Route::get('{path}', function($filename) {
        return Bust::css($filename);
    })->where('path', '.*\.css$');
    App::make('cachebuster.StripSessionCookiesFilter')->addPattern('|\.css$|');

    Route::group(['prefix' => 'me'], function() {
        Route::get('/', ['as' => 'user-profile.index', 'uses' => 'UserProfileController@index']);

        Route::group(['prefix' => '{username}'], function() {
            Route::get('/', ['as' => 'user-profile.show', 'uses' => 'UserProfileController@favorites']);
            Route::get('favorites', ['as' => 'user-profile.favorites', 'uses' => 'UserProfileController@favorites']);
            Route::get('recipes', ['as' => 'user-profile.recipes', 'uses' => 'UserProfileController@recipes']);
        });
    });

    Route::group(['prefix' => 'settings'], function() {
        Route::get('/', ['as' => 'user-settings.index.edit', 'uses' => 'UserSettingController@indexEdit']);
        Route::put('/', ['as' => 'user-settings.index.update', 'uses' => 'UserSettingController@indexUpdate']);

        Route::get('email', ['as' => 'user-settings.email.edit', 'uses' => 'UserSettingController@emailEdit']);
        Route::put('email', ['as' => 'user-settings.email.update', 'uses' => 'UserSettingController@emailUpdate']);

        Route::get('password', ['as' => 'user-settings.password.edit', 'uses' => 'UserSettingController@passwordEdit']);
        Route::put('password', ['as' => 'user-settings.password.update', 'uses' => 'UserSettingController@passwordUpdate']);

        Route::get('profile', ['as' => 'user-settings.profile.edit', 'uses' => 'UserSettingController@profileEdit']);
        Route::put('profile', ['as' => 'user-settings.profile.update', 'uses' => 'UserSettingController@profileUpdate']);
    });

    Route::get('email/error', ['as' => 'email-verification.error', 'uses' => 'Auth\RegisterController@getVerificationError']);
    Route::get('email/activate/{token}', ['as' => 'email-verification.check', 'uses' => 'Auth\RegisterController@getVerification', 'middleware' => ['throttle:10,10', 'clearUser']]);
    Route::get('email/resend', ['as' => 'email-verification.resend', 'uses' => 'UserSettingController@resendVerification', 'middleware' => 'throttle:5,10']);

    Route::group(['prefix' => 'login'], function() {
        Route::group(['prefix' => '{provider}', 'where' => ['provider' => '[a-z]+']], function() {
            Route::get('/', ['as' => 'oauth.redirect', 'uses' => 'OAuthController@redirect']);
            Route::get('callback', ['as' => 'oauth.callback', 'uses' => 'OAuthController@callback']);
        });
    });

    Route::get('/', ['as' => 'home', 'uses' => 'RecipeController@home']);

    Route::resource('ingredients', 'IngredientController', [
        'except' => [
            'index',
            'show'
        ],
        'parameters' => [
            'ingredients' => 'token'
        ]
    ]);

    Route::get('ingredients', ['as' => 'ingredients.index', 'uses' => 'IngredientController@show']);
    Route::get('ingredients/{parameters?}', ['as' => 'ingredients.show', 'uses' => 'IngredientController@show'])->where('parameters', '(.*)');

    Route::resource('recipes', 'RecipeController', ['except' => ['show']]);
    Route::get('recipes/{token}/{slug?}', ['as' => 'recipes.show', 'uses' => 'RecipeController@show'])->where('token', '[a-zA-Z0-9-]+')->where('slug', '[a-z0-9-]+');

    Route::group(['prefix' => 'ajax'], function() {
        Route::post('search/{type?}', ['before' => 'csrf', 'middleware' => 'throttle:30,5', 'as' => 'search-ajax', 'uses' => 'SearchController@ajax'])->where('type', '[A-Za-z]+');

        Route::post('recipe-image', ['before' => 'csrf', 'middleware' => 'throttle:15,5', 'as' => 'ajax_recipe_image', 'uses' => 'RecipeImageController@store']);

        Route::post('profile-image', ['before' => 'csrf', 'middleware' => 'throttle:15,5', 'as' => 'ajax_profile_image', 'uses' => 'UserSettingController@image']);

        Route::post('recipe-favorite', ['before' => 'csrf', 'middleware' => 'throttle:50,5', 'as' => 'ajax_recipe_favorite', 'uses' => 'UserFavoriteRecipeController@store']);
    });

    Route::post('search/{type?}', ['middleware' => 'throttle:30,5', 'as' => 'search', 'uses' => 'SearchController@search'])->where('type', '[A-Za-z]+');

//    Route::resource('occasions', 'OccasionController');

    Route::get('privacy', function() {echo 'Coming soon - Privacy Policy';});
    Route::get('terms', function() {echo 'Coming soon - Terms of Service';});
});

resources/views/layouts/alert.blade.php
<div class="container">
    <div class="row">
        <div class="col-12">
            <div id="alert-wrapper" class="alert-wrapper">
                <?php if (Session::has('success') || Session::has('info') || Session::has('warning') || Session::has('danger') || Session::has('status')) : ?>
                    <?php
                        if (Session::has('success')) {
                            $message = Session::get('success');
                            $message_type = 'success';
                        } elseif (Session::has('info')) {
                            $message = Session::get('info');
                            $message_type = 'info';
                        } elseif (Session::has('warning')) {
                            $message = Session::get('warning');
                            $message_type = 'warning';
                        } elseif (Session::has('danger')) {
                            $message = Session::get('danger');
                            $message_type = 'danger';
                        } elseif (Session::has('status')) {
                            $message = Session::get('status');
                            $message_type = 'success';
                        }
                    ?>
                <div class="alert alert-{{ $message_type }} alert-dismissible fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {!! $message !!}
                </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/content.blade.php
<div id="content" class="content">
    <div class="container">
        @if(View::hasSection('content-top'))
        <div class="row">
            <div class="col-12">
                @yield('content-top')
            </div>
        </div>
        @endif

        <div class="row">
        @if(View::hasSection('sidebar-left'))
            <div class="col-12 col-md-4 col-lg-3">
                @yield('sidebar-left')
            </div>
            <div class="col-12 col-md-8 col-lg-9">
                @yield('content')
            </div>
        @elseif(View::hasSection('sidebar-right'))
            <div class="col-12 col-md-8 col-lg-9">
                @yield('content')
            </div>
            <div class="col-12 col-md-4 col-lg-3">
                @yield('sidebar-right')
            </div>
        @elseif(View::hasSection('content-left'))
            <div class="col-12 col-md-6">
                @yield('content-left')
            </div>
            <div class="col-12 col-md-6">
                @yield('content-right')
            </div>
        @else
            <div class="col-12">
                @yield('content')
            </div>
        @endif
        </div>
    </div>
</div>

<div class="clearfix"></div>

resources/views/layouts/footer.blade.php
<div class="footer clearfix">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
                &copy; {{ date('Y') }} <a class="navbar-brand" href="{{ url('/') }}">{{ config('app.name') }}</a>
            </div>

            <div class="col-12 mt-3 col-md-6 mt-md-0">
                <div class="social-media-regular">
                    <a href="https://www.facebook.com/MadCocktailCom/" target="_blank">
                        <i class="fa fa-facebook" title="Facebook" aria-hidden="true"></i>
                    </a>
                    <a href="https://twitter.com/MadCocktailCom" target="_blank">
                        <i class="fa fa-twitter" title="Twitter" aria-hidden="true"></i>
                    </a>
                    <a href="https://www.pinterest.com/madcocktail/" target="_blank">
                        <i class="fa fa-pinterest-p" title="Pinterest" aria-hidden="true"></i>
                    </a>
                    <a href="https://www.instagram.com/madcocktailcom/" target="_blank">
                        <i class="fa fa-instagram" title="Instagram" aria-hidden="true"></i>
                    </a>
                    <a href="https://www.reddit.com/user/MadCocktail/" target="_blank">
                        <i class="fa fa-reddit-alien" title="Reddit" aria-hidden="true"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/header.blade.php
<div class="header">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="navbar navbar-toggleable-md navbar-inverse">
                    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="{{ url('/') }}">{{ config('app.name') }}</a>
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('ingredients.index') }}">Ingredients</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('recipes.index') }}">Recipes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('recipes.create') }}">Add Cocktail</a>
                            </li>
                        </ul>

                        <ul class="navbar-nav order-last ml-lg-2">
                        @if (Auth::check())
                            @php $image = (!empty(Auth::user()->image)) ? Auth::user()->image : 'default-user-20170328.jpg'; @endphp
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('user-profile.show', Auth::user()->username) }}">
                                    Profile
                                    <span class="nav-item-icon"><img class="image-icon image-icon-small" src="{{ route('imagecache', ['template' => 'user-small', 'filename' => $image]) }}" alt=""></span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('user-settings.index.edit') }}">@if(Auth::user()->role){{ 'Admin' }}@else{{ 'Settings' }}@endif</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>
                                <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">{{ csrf_field() }}</form>
                            </li>
                        @else
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">Login</a>
                            </li>
                        @endif
                        </ul>

                        @include('layouts.search')
                    </div>
                </nav>
            </div>
        </div>
    </div>
</div>

@if(View::hasSection('breadcrumb'))
    <div class="breadcrumb-wrapper">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    @yield('breadcrumb')
                </div>
            </div>
        </div>
    </div>
@endif

resources/views/layouts/master.blade.php
@php
    $social_image = route('imagecache', ['template' => 'share', 'filename' => 'mad-cocktail.gif']);
@endphp
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="content-language" content="en" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta property="og:site_name" content="{{ config('app.name') }}" />
    <meta property="fb:app_id" content="{{ config('services.facebook.client_id') }}" />
    <meta property="og:url" content="@yield('og-url', url()->full())" />
    {{--<meta property="og:type" content="@yield('og-type')" />--}}
    <meta property="og:title" content="@yield('title')" />
    <meta property="og:description" content="@yield('og-description')" />
    <meta property="og:image" content="@yield('og-image', $social_image)" />
    <meta property="og:image:secure_url" content="@yield('og-image', $social_image)" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="627" />

    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="{{ '@'.config('services.twitter.via') }}" />
    <meta name="twitter:url" content="@yield('og-url', url()->full())">
    <meta name="twitter:title" content="@yield('title')">
    <meta name="twitter:description" content="@yield('og-description')">
    <meta name="twitter:image" content="@yield('og-image', $social_image)">

    <title>@yield('title') | {{ config('app.name') }}</title>

    <link href="https://fonts.googleapis.com/css?family=Oxygen:700|Source+Sans+Pro:400{{--,400i--}},600" rel="stylesheet">

    <link rel="stylesheet" href="{{ Bust::url('/css/vendor/bootstrap.css', true) }}">
    {{--<link rel="stylesheet" href="{{ Bust::url('/css/vendor/font-awesome.css', true) }}">--}}
@yield('style')
    <link rel="stylesheet" href="{{ Bust::url('/css/style.css', true) }}">

    <link rel="shortcut icon" href="{{ Bust::url('/favicon.ico', true) }}">

@yield('script-top')
</head>
<body>

    @include('layouts.header')

    @include('layouts.alert')

    @include('layouts.content')

    @include('layouts.footer')

    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{{ Bust::url('/js/vendor/jquery-3.1.1.min.js', true) }}"><\/script>')</script>
    <script src="{{ Bust::url('/js/plugins-min.js', true) }}"></script>
    <script src="{{ Bust::url('/js/vendor/bootstrap.min.js', true) }}"></script>
    <script src="{{ Bust::url('/js/script-min.js', true) }}"></script>
@yield('script-bottom')

    @if(!empty(config('services.google.analytics')))
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', '{{ config('services.google.analytics') }}', 'auto');
        ga('send', 'pageview');
    </script>
    @endif
</body>
</html>

resources/views/layouts/recipe-card.blade.php
@if (!empty($recipe))
    @php
        $class_blur = '';

        if (!empty($recipe->image)) {
            $image = $recipe->image;
            $class_blur = ' image-blur';
        } else {
            $image = 'default-cocktail-glass.jpg';
        }

        $image_color = (!empty($recipe->color)) ? 'style="background-color:'.$recipe->color.';" ' : '';
    @endphp
<div class="recipe card">
    <div class="image">
        <a href="{{ route('recipes.show', ['token' => $recipe->token, 'slug' => $recipe->slug]) }}">
            <img {!! $image_color !!}class="card-img-top img-fluid{{$class_blur}}" data-original="{{ route('imagecache', ['template' => 'lists', 'filename' => $image]) }}" src="{{ route('imagecache', ['template' => 'lists-tiny', 'filename' => $image]) }}" alt="">
        </a>
        <form role="form" @if(Auth::check()) class="recipe-favorite login-recipe-favorite" method="POST" @else class="recipe-favorite" method="GET" @endif action="{{ route('login') }}">

            @if(Auth::check())
            <div class="hidden-xs-up">
                <input type="text" name="id" value="{{ $recipe->token }}">
            </div>
            @endif
            <button type="submit" class="btn-reset recipe-favorite-btn @if(!empty($favorite_recipes)){{ isset($favorite_recipes[$recipe->id]) ? 'recipe-favorite-btn-on' : '' }}@endif"><i class="fa fa-heart-o" aria-hidden="true"></i></button>
        </form>
    </div>
    <div class="card-block">
        <a href="{{ route('recipes.show', ['token' => $recipe->token, 'slug' => $recipe->slug]) }}">
            <h4 class="card-title">{{ $recipe->title }}</h4>
        </a>
        <p class="card-text">{{ Helper::nl2empty($recipe->description).' '.Helper::nl2empty($recipe->directions) }}</p>
    </div>
    @if (!empty($recipe->username))
    <div class="card-footer">
        <small class="text-muted">
            @php $author = (!empty($recipe->user_display_name)) ? $recipe->user_display_name : $recipe->username; @endphp
            <div class="d-flex align-items-center">
                <a class="d-flex" href="{{ route('user-profile.show', ['username' => $recipe->username]) }}">
                @if (!empty($recipe->user_image))
                    <img class="image-icon image-icon-small d-inline-block" src="{{ route('imagecache', ['template' => 'user-small', 'filename' => $recipe->user_image]) }}" alt="">
                @else
                    <span style="background-color: {{ $random_color[$recipe->user_id] ?: Helper::random_color() }};" class="image-icon image-icon-small d-inline-block"></span>
                @endif
                </a>

                <span class="ml-2">Recipe by <a href="{{ route('user-profile.show', ['username' => $recipe->username]) }}">{{ $author }}</a></span>
            </div>
        </small>
    </div>
    @endif
</div>
@endif

resources/views/layouts/search.blade.php
<form onsubmit="return false;" id="form-search" class="autocomplete form-inline mt-2 mb-2 mt-lg-0 mb-lg-0" method="POST" action="{{ route('search') }}">
    {{ csrf_field() }}

    <div class="hidden-xs-up">
        <input type="text" name="search-id" id="search-id" class="form-control">
        <input type="text" name="search-group" id="search-group" class="form-control">
    </div>

    <div class="input-group">
        <input type="text" name="search" id="search" class="search form-control" placeholder="Search for...">
        {{--<span class="input-group-btn">--}}
            {{--<button class="btn btn-gray" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>--}}
        {{--</span>--}}
    </div>
</form>